POST http://localhost:3001/api/bed HTTP/1.1
content-type: application/json 

 {
  "type": "manual",
  "status": "Patient in discharge",
  "description": "Patient about to be discharged. Bed will be released soon"
 }