PUT http://localhost:3001/api/ward/6352cd1607fd74a45ecd9723
 content-type: application/json
 
{
  "name": "Special care unit 1 & 2",
  "section": ""
 }

#  {
#   "email": "edrissasaine366@gmail.com",
#   "password": "PASSword123",
#   "firstname": "Edrissa",
#   "minit": "Mansour",
#   "lastname": "Saine",
#   "role": "Admin"
#  }